# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/club/getAll
Accept: application/json

###

POST http://ec2-13-125-237-43.ap-northeast-2.compute.amazonaws.com:8080/club/add
Content-Type: application/json

{
  "logo_url": "src/Upload/logo_1.png",
  "info": "봉사 동아리",
  "name": "호우회"
}
###

POST http://localhost:8080/club/add
Content-Type: application/json

{
  "logo_url": "src/Upload/logo_1.png",
  "info": "봉사 동아리",
  "name": "호우회"
}

###