# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/club/getAll
Accept: application/json

###

POST http://ec2-52-78-73-194.ap-northeast-2.compute.amazonaws.com:8080/club/add
Content-Type: application/json

{
  "logo_url": "아직 못했다으아아앙",
  "info": "볼링 동아리",
  "name": "SPLIT",
  "data": "🎳가천대학교 중앙볼링동아리 SPLIT 신입부원을 모집합니다🎳\n🎳가천대학교 중앙볼링동아리 SPLIT 신입부원을 모집합니다🎳\n\n2020년 1학기를 맞이하여\n함께 볼링 즐기실 신입부원을 모집합니다❗\n\n📍가천대학교 유일무이 중앙볼링동아리\n📍학번, 나이, 실력 제한❌ (볼린이 환영)\n📍매주 수,목,금 中 원하는 날 참여\n📍타 대학 볼링 동아리와 교류전\n📍자유로운 동아리실 사용\n📍즐거운 회식 & MT 🔥\n\n이번 학기 자유로운 동아리 활동을 하고 싶다❗\n친목과 볼링을 한번에 해결하고 싶다❗\n볼링의 재미를 맛보고 싶다❗\n볼링을 배워보고 싶다❗\n\n모두 🎳SPLIT🎳으로 오시면 됩니다!\n이번 학기 즐거운 볼링 생활 같이 해요😊\n\n🔥가입지원서 : https://form.office.naver.com/form/responseView.cmd?formkey=ZjU0MWEzNWYtOThiNi00MWY5LTk4YjEtMjQ5ZDcyYjdhOGNl&sourceId=urlshare\n\n문의\n회장 박찬동 TEL.010-9111-1670\n카톡. cksehd48\n"
}

###

POST http://localhost:8080/club/add
Content-Type: application/json

{
  "logo_url": "아직 못했다으아아앙",
  "info": "봉사 동아리",
  "name": "호우회",
  "data": "💙중앙 봉사동아리 호우회💙\n안녕하세요😊 가천대학교 중앙 봉사 동아리 호우회입니다‼️\n💙2020년도 37기 호우회 부원을 모집하고 있습니다💙\n\n재미있게 봉사하며 봉사시간을 채우고 싶다⁉️\n동기, 선배, 후배들과 친해지고 싶다⁉️\nCC하고 싶고 인싸 되고싶다⁉️\n재학생, 편입생도 받아주는 동아리를 찾고 있다⁉️\n하시는 분들은 주목해주세요🎉️ \n\n호우회에서 하는 활동은🤷‍♀️?\n👉 정기적인 봉사 (월 2회)\n👉 다양한 친목활동 (마니또, 번개모임, 동아리팅)\n👉 신나고 재밌는 동아리MT\n이 외에 올해 다양하고 재밌는 행사들을 계획하고 있습니다😀\n\n🌟가입 방법 : 아래에 적힌 번호로 ‼️이름, 학과, 학번, 전화번호‼️를 보내주시면 가입 완료🤗\n\n호우회에 대해 더 궁금한 것이 있다면 부담없이 아래 번호로 언제든지 문의해주세요🙏\n\n💸회비💸 : 한 학기당 10000원 (봉사 후 회식, MT, 번개모임 등에 사용됩니다)\n"
}

###